package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);
    //定义的DAO层的方法，通过itemId来返回ItemStockDO的表记录数据对象
    ItemStockDO selectByItemId(Integer itemId);

    //新增的删减更新item_stock表库存记录的方法。返回更新成功的条目数
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 19 11:03:11 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);
}